version: "3.7"

services:
  prisma_db:
    image: postgres
    container_name: prisma_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ignitenodejs
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local